### PR TITLE
peachpie 0.9.900

### PR DESCRIPTION
**Pull request by jakubmisek**
simplified project structure, peachpie version is specified once in `global.json`

fixes hundreds of issues since 0.9.800,

### CODE REVIEW

**Comment by gordon-matt** [comment]
Oh wow! Another one. I didn't see it until now.. and I already updated to 0.9.900. I see that you've made some other changes though. I will incorporate those changes to my code soon... it's almost 4am here now.. so I'll get back to this tomorrow maybe.

**Comment by jakubmisek** [comment]
good :) yes the changes remove some unnecessary code from project files.

Now you only specify peachpie version once in `global.json`, makes it easier to update when we release `1.0.0`

thank you

**Comment by gordon-matt** [comment]
Your changes have been incorporated. Thanks

**Comment by jakubmisek** [comment]
there is `0.9.910` which fixes the `$_FILES` issue

**Pull request closed without merging**
