### PR TITLE
ResponsiveFileManager.AspNetCore

### PR DESCRIPTION
**Pull request by jakubmisek**
- proper ResponsiveFileManager ASP.NET Core API
- AddResponsiveFileManager() to set options
- UseResponsiveFileManager() to setup request pipeline
- updated PeachPie to 0.9.990

### CODE REVIEW

**Comment by jakubmisek** [comment]
Hi @gordon-matt - this is PR that introduces `ResponsiveFileManager.AspNetCore` package containing the logic for integrating ResponsiveFileManager into ASP.NET Core application. It hides all the PHP magic and provides standard API
- AddResponsiveFileManager() to set options
- UseResponsiveFileManager() to setup request pipeline

Users would reference `ResponsiveFileManager.AspNetCore` package only, and then add `app.UseResponsiveFileManager()` only.

**Comment by gordon-matt** [comment]
Fantastic! I have been meaning to do this myself for a while, but have been too busy. Thank you very much.

**Comment by gordon-matt** [comment]
Small question: Do we really want `app.UsePhp();` inside `UseResponsiveFileManager` ? It's possible maybe they want to use PeachPie for other purposes as well and then maybe we end up with 2 calls to `UsePhp`? Or maybe they want to set some `PhpRequestOptions` using the overload? Is it possible to detect if `UsePhp` has already been called once? If not, only then do we set it ourselves. What do you think?

**EDIT**: Nevermind... that would mean we have to think about `AddPhp()` in `AddResponsiveFileManager()` as well... so I am not sure if there's a perfect solution for people using PeachPie for multiple purposes. I am guessing 99% of people using this project won't be using PeachPie for anything else anyway and if they do, they can ignore the AspNetCore package and only use the base package and set the options themselves in Startup like we were doing before.

**Comment by gordon-matt** [comment]
Packages released on NuGet

**Comment by jakubmisek** [comment]
That's a good point! 

I suppose as you said, they can use `UsePhp` + `UseStaticFiles` instead of `UseResponsiveFileManager` in case they need more PHP handlers.

Or, PeachPie should provide more parameters to its API
```c#
UsePhp( string pathPrefix, Action<IPhpOptions> options = null )
// or
UsePhp( Assembly phpAssembly, Action<IPhpOptions> options = null )
// or ...
```
or something similar to MVC's `UseEndpoints`.
, so component developers like you or like our WordPress could be more specific about options in specific paths.

**Comment by gordon-matt** [comment]
@jakubmisek Yes, I was thinking of a situation where maybe someone wants to use this file manager, but then maybe later I make another project with a PHP chat room or help chat, for example.. would that even be possible to use both together? Or can PeachPie only handle one PHP application in this scenario?

**Comment by jakubmisek** [comment]
As of now, it would work normally, there would just be two handlers installed. Therefore, the second one would not be necessary.

For that case, the API I've noted above would make sense.

**Pull request merged**
