### PR TITLE
removed unnecessary files, fixed `contentFiles`, updated PeachPie

### PR DESCRIPTION
**Pull request by jakubmisek**
- updated to PeachPie 0.9.970

- project structure fixes, copy and pack files properly
  - /Website -> /ResponsiveFileManager
  - ResponsiveFileManager provides contentFiles properly, netcoreapp3.0+
  - does not (should not) include `.php` files in NuGet
  - sample aspnetcore app handles static files properly
  - static and default prior to .php request handler
  - path to `/fiemanager` static files updated, copied from NuGet/Project properly

- updated readme
  - added libman instructions (not included in VS anymore, must be done manually)
  - UseStatic() before UsePhp() (recommended)
  - path to `/filemanager` updated (it is now outside of wwwroot)

- removed local nuget feed (causes problems with building)

### CODE REVIEW

**Comment by gordon-matt** [comment]
Wow, that's a lot of changes. I am a little concerned about some of them though. For example, this one:

`does not (should not) include .php files in NuGet`

There is a good reason that I included those php files. I did not include all of the php files.. only the language files, because the Responsive File Manager was throwing errors when it could not find them.

Anyway, thanks. I will try to view and merge soon.

**Comment by gordon-matt** [comment]
Also.. all those file manager files that you deleted served a purpose as well.. While developing (example: testing a new version of RFM), then I will use the files instead of the NuGet package.. and then later when I confirmed it's working, then I will release the NuGet package and switch to that instead of the files. That's why I had both a `<PackageReference>` and a `<ProjectReference>` in the .csproj. I switch between NuGet package and normal files depending on if I am in development mode or release.

And the local NuGet feed is also useful for testing NuGet packages to make sure they work, before releasing it.

**Comment by jakubmisek** [comment]
thanks for reviewing; all these were considered.

- PeachPie will serve the language PHP files "virtually" (file_exists gets TRUE even the file is not physically there)
- during development, since "contentfiles" were fixed, files are copied to /bin by msbuild automatically

**Comment by gordon-matt** [comment]
It's working well. Nicely done, thank you. New package is on NuGet now.

**Comment by jakubmisek** [comment]
great! thank you :)

**Pull request merged**
